name: Setup env
description: composite action to setup env

runs:
  using: composite
  steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, dom, pdo, pdo_mysql
    - uses: actions/setup-node@v4
      with:
        node-version: '22'

